import getpass
from supabase import create_client, Client, PostgrestAPIError
from dotenv import load_dotenv
import argparse
import csv
import requests
from bs4 import BeautifulSoup
import time
import re
from urllib.parse import urljoin
import os

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


# generated by anthropic
class GamesCrawler:
    def __init__(self):
        self.base_url = "https://online-fix.me/games/page/"
        self.games_base = "https://online-fix.me/games/"
        self.all_game_links = []
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Connection': 'keep-alive',
        }

    def get_page(self, url):
        """Fetch a page and return BeautifulSoup object"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def get_total_pages(self, soup):
        """Extract the total number of pages from pagination"""
        if not soup:
            return 1

        # Look for pagination elements
        pagination = soup.find('nav', class_='navigation') or soup.find(
            'nav', class_='pagination')

        if pagination:
            # Find all page links
            page_links = pagination.find_all('a')
            page_numbers = []

            for link in page_links:
                href = link.get('href', '')
                text = link.get_text().strip()

                # Extract page number from URL
                match = re.search(r'/page/(\d+)/', href)
                if match:
                    page_numbers.append(int(match.group(1)))

                # Or from link text
                if text.isdigit():
                    page_numbers.append(int(text))

            if page_numbers:
                return max(page_numbers)

        # Alternative: look for "last" page link
        last_link = soup.find('a', class_='last') or soup.find(
            'a', text=re.compile(r'последняя|last', re.I))
        if last_link:
            href = last_link.get('href', '')
            match = re.search(r'/page/(\d+)/', href)
            if match:
                return int(match.group(1))

        return 1

    def is_valid_game_link(self, href):
        """Check if the link is a valid game link (not a tag/filter page)"""
        if not href:
            return False

        # Must start with games base URL
        if not href.startswith(self.games_base):
            return False

        # Exclude pagination pages
        if '/page/' in href:
            return False

        # Exclude tag/filter pages (like 'officialservers', 'coop', etc.)
        # These typically have format: /games/tag_name/
        # Valid game links have format: /games/tag_name/id-game-name.html

        # Extract path after /games/
        path_after_games = href.replace(self.games_base, '')

        # Valid game links should end with .html
        if not path_after_games.endswith('.html'):
            return False

        return True

    def extract_game_links(self, soup):
        """Extract all valid game links from a page"""
        if not soup:
            return []

        game_links = []

        # Find all links on the page
        all_links = soup.find_all('a', href=True)

        for link in all_links:
            href = link.get('href', '')

            # Make absolute URL if relative
            if href.startswith('/'):
                href = urljoin("https://online-fix.me", href)

            # Check if it's a valid game link
            if self.is_valid_game_link(href):
                if href not in game_links:
                    game_links.append(href)

        return game_links

    def crawl_page(self, page_num):
        """Crawl a specific page number"""
        url = f"{self.base_url}{page_num}/"
        print(f"Crawling page {page_num}: {url}")

        soup = self.get_page(url)
        if soup:
            links = self.extract_game_links(soup)
            print(f"  Found {len(links)} game links")
            return links, soup
        return [], None

    def crawl_all_pages(self, delay=1.0, max_pages=None):
        """Crawl all pages starting from page 1"""
        print("Starting crawler...")
        print("="*50)

        # First, get page 1 to determine total pages
        links, soup = self.crawl_page(1)
        self.all_game_links.extend(links)

        # Determine total pages
        total_pages = self.get_total_pages(soup)
        print(f"\nTotal pages detected: {total_pages}")

        if max_pages:
            total_pages = min(total_pages, max_pages)
            print(f"Limiting to {max_pages} pages")

        print("="*50)

        # Crawl remaining pages
        for page_num in range(2, total_pages + 1):
            time.sleep(delay)  # Be respectful to the server
            links, _ = self.crawl_page(page_num)

            for link in links:
                if link not in self.all_game_links:
                    self.all_game_links.append(link)

        # Remove duplicates while preserving order
        self.all_game_links = list(dict.fromkeys(self.all_game_links))

        print("\n" + "="*50)
        print(f"Crawling complete!")
        print(f"Total unique game links found: {len(self.all_game_links)}")

        return self.all_game_links

    def save_links_to_file(self, filename="game_links.txt"):
        """Save all collected links to a file"""
        with open(filename, 'w', encoding='utf-8') as f:
            for link in self.all_game_links:
                f.write(link + '\n')
        print(f"Links saved to {filename}")

    def print_links(self, limit=None):
        """Print collected links"""
        links_to_print = self.all_game_links[:
                                             limit] if limit else self.all_game_links

        print("\nCollected Game Links:")
        print("-"*50)
        for i, link in enumerate(links_to_print, 1):
            print(f"{i}. {link}")

        if limit and len(self.all_game_links) > limit:
            print(f"... and {len(self.all_game_links) - limit} more links")


class GameData:
    def __init__(self, COOKIES=""):
        self.url = ""
        self.data = {
            "title": "",
            "link": "",
            "tag": "",
            "fixLink": ""

        }
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Connection': 'keep-alive',
            'Cookie': COOKIES
        }

    def get_page(self, url):
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            self.url = url
            return BeautifulSoup(response.content, 'html.parser')
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def get_data(self, url):
        soup = self.get_page(url)
        self.data["link"] = self.url
        if soup.find(id="news-title"):
            self.data["title"] = soup.find(id="news-title").text.strip()
        else:
            self.data["title"] = "None"
        self.data["tag"] = self.url.split("/")[4]

        download_link = soup.select_one(
            'div.quote a[href^="https://uploads.online-fix.me:2053/uploads/"]')
        if download_link:
            self.data["fixLink"] = download_link["href"]+"Fix%20Repair/"
        else:
            print("No fix available for: ", self.url)
            self.data["fixLink"] = "None"

    def download_fix_file(self):
        if self.data["fixLink"] == "None":
            return

        fix_url = self.data["fixLink"]
        try:
            # print(f"Getting fix from: {fix_url}")
            headers = self.headers.copy()
            headers['Referer'] = self.data["link"]

            response = requests.get(
                fix_url, headers=headers, timeout=30, stream=True)
            response.raise_for_status()

            soup = BeautifulSoup(response.text, 'html.parser')

            link = soup.find_all("a", href=True)
            if len(link) == 2:
                self.data["fixLink"] = fix_url + link[1]['href']
            else:
                self.data["fixLink"] = "None"
            return self.data

        except requests.RequestException as e:
            print(f"Error downloading: {e}")
            return None


def check_new_games_supabase(links_list, supabase):
    """Sync just links without extracting title/tag"""

    batch_size = 100

    for i in range(0, len(links_list), batch_size):
        batch_links = links_list[i:i + batch_size]
        try:
            # Check existing
            existing = supabase.table("games").select(
                "link").in_("link", batch_links).execute()
            existing_links = {x['link'] for x in existing.data}

            # Filter new
            new_links = [
                link for link in batch_links if link not in existing_links]

            """ if new_links:
                # Insert just the links
                new_games = [{"link": link} for link in new_links]
                supabase.table("games").insert(new_games).execute()
                added += len(new_games)
                print(f"✓ Batch {i//batch_size + 1}: {len(new_games)} added") """

        except Exception as e:
            print(f"Error: {e}")
    return new_links


def main():
    parser = argparse.ArgumentParser(
        prog='ProgramName',
        description='What the program does',
        epilog='Text at the bottom of help')

    parser.add_argument('-c', '--crawl')
    args = parser.parse_args()

    load_dotenv()

    url: str = os.environ.get("SUPABASE_URL")
    key: str = os.environ.get("SUPABASE_KEY")

    email: str = os.environ.get("SUPABASE_AUTH_EMAIL")
    password: str = os.environ.get("SUPABASE_AUTH_PASSWORD")

    is_github_actions = os.getenv("GITHUB_ACTIONS") == "true"

    supabase: Client = create_client(url, key)

    if not email and not password:
        print("Admin login necessary to update database")
        email = input("Email: ")
        password = getpass.getpass(prompt='Password: ')

    response = supabase.auth.sign_in_with_password(
        {
            "email": email,
            "password": password,
        }
    )

    print("Logged in succesfully")

    if not args.crawl:
        print("Starting crawl of website")
        crawler = GamesCrawler()
        crawled_links = crawler.crawl_all_pages(delay=1.0, max_pages=None)
        crawler.print_links(limit=20)
    else:
        with open(args.crawl) as file:
            crawled_links = file.read().splitlines()

    print("Starting scrape of list")

    print("Getting cookies...")

    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--width=1920")
    options.add_argument("--height=1080")

    driver = webdriver.Firefox(options=options)

    driver.get("https://online-fix.me/")
    cookie_string = "; ".join(
        [f"{c['name']}={c['value']}" for c in driver.get_cookies()])
    # print(cookie_string)
    driver.quit()

    game_data = GameData(cookie_string)
    new_games = check_new_games_supabase(crawled_links, supabase)
    nmbLines = len(new_games)
    print(f"New games found to crawl: {nmbLines}")
    for i, line in enumerate(new_games):
        game_data.get_data(line)
        game_data.download_fix_file()
        print(f"Scrapping {game_data.data["title"]}. {i+1}/{nmbLines}")

        supabase.table("games").upsert(
            game_data.data,
            on_conflict="title"
        ).execute()

        print("Program finished correclty")
        """ with open("game_fix.csv", mode='a', newline='', encoding="utf-8") as file:
                    writer = csv.writer(file)
                    writer.writerow(game_data.data.values())  # Write values
                time.sleep(0.5) """


if __name__ == "__main__":
    main()
